//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessmentHelper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int MainForm_PosX {
            get {
                return ((int)(this["MainForm_PosX"]));
            }
            set {
                this["MainForm_PosX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int MainForm_PosY {
            get {
                return ((int)(this["MainForm_PosY"]));
            }
            set {
                this["MainForm_PosY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int MainForm_SizeHeight {
            get {
                return ((int)(this["MainForm_SizeHeight"]));
            }
            set {
                this["MainForm_SizeHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int MainForm_SizeWidth {
            get {
                return ((int)(this["MainForm_SizeWidth"]));
            }
            set {
                this["MainForm_SizeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int FormAddResult_PosX {
            get {
                return ((int)(this["FormAddResult_PosX"]));
            }
            set {
                this["FormAddResult_PosX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int FormAddResult_PosY {
            get {
                return ((int)(this["FormAddResult_PosY"]));
            }
            set {
                this["FormAddResult_PosY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int FormAddResult_SizeWidth {
            get {
                return ((int)(this["FormAddResult_SizeWidth"]));
            }
            set {
                this["FormAddResult_SizeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int FormAddResult_SizeHeight {
            get {
                return ((int)(this["FormAddResult_SizeHeight"]));
            }
            set {
                this["FormAddResult_SizeHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int FormGiveAnswer_PosX {
            get {
                return ((int)(this["FormGiveAnswer_PosX"]));
            }
            set {
                this["FormGiveAnswer_PosX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int FormGiveAnswer_PosY {
            get {
                return ((int)(this["FormGiveAnswer_PosY"]));
            }
            set {
                this["FormGiveAnswer_PosY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int FormGiveAnswer_SizeWidth {
            get {
                return ((int)(this["FormGiveAnswer_SizeWidth"]));
            }
            set {
                this["FormGiveAnswer_SizeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int FormGiveAnswer_SizeHeight {
            get {
                return ((int)(this["FormGiveAnswer_SizeHeight"]));
            }
            set {
                this["FormGiveAnswer_SizeHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int FormAddQuestion_PosX {
            get {
                return ((int)(this["FormAddQuestion_PosX"]));
            }
            set {
                this["FormAddQuestion_PosX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int FormAddQuestion_PosY {
            get {
                return ((int)(this["FormAddQuestion_PosY"]));
            }
            set {
                this["FormAddQuestion_PosY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int FormAddQuestion_SizeWidth {
            get {
                return ((int)(this["FormAddQuestion_SizeWidth"]));
            }
            set {
                this["FormAddQuestion_SizeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int FormAddQuestion_SizeHeight {
            get {
                return ((int)(this["FormAddQuestion_SizeHeight"]));
            }
            set {
                this["FormAddQuestion_SizeHeight"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\master1\\share\\andi\\test")]
        public string SharedPath {
            get {
                return ((string)(this["SharedPath"]));
            }
        }
    }
}
